version: "2.1"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  startings: [html, head, body]
  endings: [html, head, body]

#build
source: src
destination: _site
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown

plugins:
  - jekyll-autoprefixer
  
autoprefixer:
#   only_production: true
  browsers: 
    - "Safari >= 7"
    - "Chrome >= 55"