version: "1.2"

compress_html:
  clippings: all
  startings: [html, head, body]
  endings: [html, head, body]

#build
source: src
destination: _site
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown

plugins:
  - uglifier