#head 
title: Coin Ticker
description: "Coin Ticker is a safari extension that allows you to track cryptocurrency prices."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
version: "1.0.2"

#build
source: src
destination: _site
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown